Inherit dox-style in .rubocop.yml
This PR was automatically generated in order to inherit a unified set of styles.

Please pull this branch, Fetching gem metadata from https://gem.fury.io/doximity/..
Fetching gem metadata from https://gem.fury.io/doximity/.
Fetching gem metadata from http://rubygems.org/.........
Fetching gem metadata from https://gem.fury.io/doximity/.
Fetching gem metadata from https://gem.fury.io/doximity/.
Fetching gem metadata from http://rubygems.org/...
Resolving dependencies....
Fetching rake 10.4.2
Installing rake 10.4.2
Using i18n 0.7.0
Fetching json 1.8.3
Installing json 1.8.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/jklein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
/Users/jklein/.rbenv/versions/2.4.1/bin/ruby -r ./siteconf20180214-78571-khf4ug.rb extconf.rb
creating Makefile

current directory: /Users/jklein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/jklein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c:861:25: error: use of undeclared identifier 'rb_cFixnum'
    } else if (klass == rb_cFixnum) {
                        ^
generator.c:863:25: error: use of undeclared identifier 'rb_cBignum'
    } else if (klass == rb_cBignum) {
                        ^
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2147:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2333:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2205:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2171:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2166:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2162:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2147:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2333:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2205:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2171:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2167:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs+1, varc, vari+1))
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2162:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2147:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2333:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2205:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2172:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs+1, varc, vari+1))
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2166:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2162:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2147:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2333:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2205:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2171:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2166:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2162:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2147:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2333:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2205:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2171:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2166:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2162:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2147:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2333:9: note: expanded from macro 'rb_scan_args0'
                     (rb_scan_args_verify(fmt, varc), vars))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2205:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 5 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2171:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2166:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jklein/.rbenv/versions/2.4.1/include/ruby-2.4.0/ruby/ruby.h:2162:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 warnings and 2 errors generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/jklein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-1.8.3 for inspection.
Results logged to
/Users/jklein/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0-static/json-1.8.3/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

In Gemfile:
  attachinary was resolved to 1.3.1, which depends on
    rails was resolved to 4.2.3, which depends on
      actionmailer was resolved to 4.2.3, which depends on
        actionpack was resolved to 4.2.3, which depends on
          actionview was resolved to 4.2.3, which depends on
            rails-dom-testing was resolved to 1.0.6, which depends on
              rails-deprecated_sanitizer was resolved to 1.0.3, which depends on
                activesupport was resolved to 4.2.3, which depends on
                  json, and resolve any conflicts with adding the dox-style gem.

If you had an existing , those styles still exist. Please remove any existing styles that duplicate or conflict with the styles found in [the dox-style .rubocop.yml](https://github.com/doximity/dox-style/blob/master/.rubocop.yml)